### ISSUE TITLE
MMMM formatting doesn't work in cljs

### ISSUE THREAD

**Issue by stevebuik** [henryw374/cljc.java-time#13]
put together a test case here https://github.com/stevebuik/date-formatting

have tested using the latest release 0.1.11 (in another repo) and the problem still exists

**Comment by henryw374** [comment]
Hi,

I've tried out "MMMM" formatting in my local project and it is working fine, so yes I think it is the versions of deps you have.

 There was a recent release of cljc.java-time, 0.1.11, where the js-joda deps were bumped to the latest, and also no longer need to be manually added to package.json, see http://widdindustries.com/tick-with-shadow-just-works/ . So I think what you need to do is just  remove all the deps from package.json apart from locale, e.g.  "@js-joda/locale_en-us" "3.1.1" and bump cljc.java-time.

**Comment by stevebuik** [comment]
Thanks for the quick response. 

Your blog post is why I re-visited this. I hoped to ditch my workaround of calling another NPM lib for date-time formatting.

I've updated the test repo and it still reproduces with the latest release. I'll be delighted if you can show me what I've missed or if you can reproduce the problem from the test repo.

https://github.com/stevebuik/date-formatting/blob/master/src/formatting_test.cljc

Odd that it works in your local project. I wonder what magic combination of clj/npm deps allows that to happen?

**Comment by henryw374** [comment]
ok i think this is working: 

see https://github.com/henryw374/date-formatting

```
Testing formatting-test

Ran 1 tests containing 1 assertions.
0 failures, 0 errors.
===============================================
[:test] Build completed. (54 files, 1 compiled, 0 warnings, 2.85s)
=> :watching
```

**Comment by stevebuik** [comment]
Fantastic. I can confirm this works in this project and in both my node.js lambdas and browser clients.

Thanks for showing me the way!
