### ISSUE TITLE
How to create a zone-id (ZoneId)?

### ISSUE THREAD

**Issue by alza-bitz** [henryw374/cljc.java-time#2]
Hi there,

I want to use `cljc.java-time.instant/at-zone`, but for that I need a `zone-id`..

However, when I look at the api for `cljc.java-time.zone-id`, I can't see an `of` function matching the Java API to create a zone id from a string?

Also, I'm using ClojureScript/NodeJS and `cljc.java-time.zone-id/get-available-zone-ids` is empty? On Clojure/Java it's populated as I would expect. I've required `[cljsjs.js-joda-timezone]` as I thought that might be needed to load in the timezone stuff, but `get-available-zone-ids` is still empty.

Ideas?

Thanks!

p.s. I'm trying to use `cljc.java-time` as I was trying to use `tick`, but I encountered issues so I thought I'd try to use this lib directly.. The tick issue is here: https://github.com/juxt/tick/issues/35

**Comment by henryw374** [comment]
Hi, I've just added a bit to the readme to explain where there is no `of` function in the zone-id ns. The workaround will be to drop to interop. Using the same requires as the zone-id ns. 

```(. ZoneId of "Europe/London")```

but... as I say in the tick issue 35, your zones are not getting loaded for some reason. `cljc.java-time.zone-id/get-available-zone-ids` works, once the zones are loaded

**Comment by henryw374** [comment]
I am going to fix this and the other cases of the same type

**Comment by henryw374** [comment]
there is now a zone-id/of fn in latest clojars lib. I'll address the original issue in tick #35
