### ISSUE TITLE
Avoid calling `Class/forName` on every invocation

### ISSUE THREAD

**Issue by SevereOverfl0w** [henryw374/cljc.java-time#20]
Currently, cljc.java-time.local-date/at-time calls `Class/forName` on every invocation for it's instance check.  This isn't particularly fast and impacts hot loops, instead it could use a `(let)` around itself or perhaps just refer to the class name in full?

**Comment by SevereOverfl0w** [comment]
The advanced version of this might be to define a protocol that reverses the arguments for the dispatch and then calls that.  That's probably faster than `instance?`

**Comment by henryw374** [comment]
using `instance?` now on master if you can try that?

doing this has revealed some problems with babashka (it is missing some classes) so I might hold off on release while i think about what to do

**Comment by henryw374** [comment]
0.1.16 released
