### ISSUE TITLE
allow disabling helpful exception messages on CLJS

### ISSUE THREAD

**Issue by terinjokes** [henryw374/cljc.java-time#22]
It seems there's no implementation for CLJS in  `(helpful-exception-messages?) `, meaning there is no way to disable the insertion of the helpful exception messages in a release build.

**Comment by henryw374** [comment]
the exception messages are en/disabled at cljs compilation time - iow in clojure. if you set the system prop `cljc.java-time.disable-helpful-exception-messages` before doing release build, they will be removed
