### ISSUE TITLE
Second Clojars link possibly out of date/confusing

### ISSUE THREAD

**Issue by ryantate** [henryw374/cljc.java-time#23]
Hello, This looks like a fine library, thanks for making it. 

I clicked the [link on the README.md under the "Usage" header titled "Get it from clojars"](https://clojars.org/cljc.java-time) to figure out the package.clj dependency format, and the latest version has the version string "RENAMED," so I am unclear if I am meant to begin using a clojars package symbol other than cljc.java-time?

I also noticed that while version 0.1.18 is available from clojars, there is a tag dating to June on the github repo for a version 0.1.21, I am not clear if that is meant to be available through clojars or not (it is not available as `[cljc.java-time "0.1.21"]`).

Just thought I'd flag it in case the "RENAMED" was an accidental version string, or in case the clojars link is now supposed to point somewhere else. For the moment I am just using (or about to start playing with) 0.1.18 which seems to have installed fine.

**Comment by ryantate** [comment]
Ah, I have just noticed the image at the top of the readme has the correct dependency vector, and links to the right place, so perhaps the link further down just needs an update.

`[com.widdindustries/cljc.java-time "0.1.21"]`

(I now recall something about clojars starting to require proper namespaces, presumably this shift is related to that. I went ahead and re-titled the Issue and updated the first post to be more specific about the link I'm referring to.)

**Comment by henryw374** [comment]
Thanks. yes renamed bc clojars namespace thing. removed the old link now
