### ISSUE TITLE
Some functions do not type hint correctly.

### ISSUE THREAD

**Issue by awkay** [henryw374/cljc.java-time#7]
One example is in PR #6

**Comment by awkay** [comment]
BTW: you left no great way for running tests in watch mode...I tried the --watch on the test runner you're using, and it just crashed.  Highly recommend shadow-cljs...the browser testing there is easy to set up, and fantastic to work with.

I set that up in my clone here: https://github.com/awkay/cljc.java-time/commit/3c48c876fb0c5b69a8370c3170a2aa72ffc795bb

Just type `make` and go to localhost:9002

Of course, you could do the figwheel main thing as well.

**Comment by henryw374** [comment]
thanks. so far I'm mostly using figwheel, but also testing with shadow as well. mostly I'm doing this via the tick project... but now this lib is taking on it's own life I ought to add the configs here as well.

**Comment by henryw374** [comment]
ok, released 0.1.5 that should fix the problem. 

I also incorporated your shadow setup, thanks again!

**Comment by awkay** [comment]
Cool. You're welcome. Thanks for working on the date/time stuff.  It's so useful to have consistent types for dates in cljc.
